
all: quickintro

quickintro:
	@echo "Read me first, please"

dist: distdir
	tar chof - $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	-chmod -R a+w $(distdir) >/dev/null 2>&1; rm -rf $(distdir)

test: test-openbsd-4.0

test-openbsd-4.0:
	rsync -avubz ./ openbsd40:/home/chema/tmp/pcaptxt

test-freebsd-6.2:
	rsync -avubz ./ freebsd62:/home/chema/tmp/pcaptxt

